--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/golang:1.9"
      - 
        environment: 
          - MYSQL_ROOT_PASSWORD: development_pass
          - MYSQL_DATABASE: scion_coord_test

        image: "circleci/mysql:5.7"
    steps: 
      - checkout
      - run: "cp conf/development.conf.default conf/development.conf"
      - run:
         name: Wait for db
         command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: "go get github.com/kardianos/govendor"
      - run: "govendor sync -v"
      - run: "go test -v ./..."
    working_directory: "/go/src/github.com/netsec-ethz/scion-coord"
version: 2
